FROM python:3.6

RUN git clone --depth=1 --branch=0.3.1 https://github.com/ingydotnet/git-subrepo /tmp/git-subrepo \
        && cd /tmp/git-subrepo \
        && make install \
        && cd - \
        && rm -rf /tmp/git-subrepo
